version: '3'
services:
  mongo:
    container_name: mongo
    image: mongo:latest
    ports:
      - 27017:27017
    networks:
      - node_network
  app1:
    container_name: coba
    image: rezida0507/sejutacita_technicaltest_rezida_app:1.0
    ports:
      - 80:3000
    depends_on:
      - mongo
    networks:
      - node_network

networks:
  node_network:
    name: node_network


  # app:
  #   container_name: TechnicalTest_Rezida
  #   restart: always
  #   build: .
  #   ports:
  #     - '80:3000'
  #   links:
  #     - mongo
  # mongo:
  #   container_name: mongo
  #   image: mongo
  #   ports:
  #     - '27017:27017'