apiVersion: v1
kind: Pod
metadata:
  name: sejutacitarezida
spec:
  containers:
    - name: mongo
      image: mongo
      ports:
        - containerPort: 27017
    - name: test
      image: rezida0507/sejutacita_technicaltest_rezida_app:1.0
      ports:
        - containerPort: 80
